import type { Food, HealthProfile } from "./types";

export const demoProfile: HealthProfile = {
  id: "demo-profile",
  nickname: "Alex",
  age: 35,
  sex: "prefer-not",
  heightCm: 172,
  weightKg: 86,
  bmi: 29.1,
  activityLevel: "light",
  goal: "manage-blood-sugar",
  medicalConditions: ["diabetes", "hypertension"],
  allergies: [],
  dietaryPreferences: ["low-sugar", "low-sodium"],
  clinicianLimits: {
    calorieTarget: 2000,
    sodiumLimitMg: 1500,
    sugarLimitG: 30,
    saturatedFatLimitG: 20,
    proteinTargetG: 100,
    carbTargetG: 220,
    fibreTargetG: 30,
  },
  consentMedicalDataStored: true,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

const now = new Date().toISOString();

export const demoFoods: Food[] = [
  {
    id: "demo-cookies",
    source: "demo",
    name: "Chocolate Chip Cookies",
    brand: "Demo Bakery",
    servingSize: "2 cookies (30g)",
    servingGrams: 30,
    nutrition: {
      calories: 150,
      protein: 1.5,
      carbs: 20,
      sugar: 12,
      fat: 7,
      saturatedFat: 4,
      fibre: 0.5,
      sodium: 110,
    },
    ingredients:
      "Wheat flour, sugar, palm oil, chocolate chips (sugar, cocoa mass, cocoa butter, emulsifier: soy lecithin), invert sugar syrup, raising agents (E500, E503), salt, flavouring.",
    allergens: ["wheat", "soy", "may contain milk"],
    additives: ["E500", "E503", "soy lecithin"],
    nutriscore: "e",
    novaGroup: 4,
    dataConfidence: "high",
    createdAt: now,
  },
  {
    id: "demo-burger-meal",
    source: "demo",
    name: "Classic Cheeseburger Meal",
    brand: "Fast Food Co.",
    servingSize: "1 meal (burger + medium fries)",
    nutrition: {
      calories: 920,
      protein: 28,
      carbs: 102,
      sugar: 9,
      fat: 44,
      saturatedFat: 15,
      fibre: 6,
      sodium: 1480,
    },
    ingredients:
      "Beef patty, cheese, bun (wheat flour, sugar, yeast), pickles, ketchup, mustard, potatoes, vegetable oil, salt.",
    allergens: ["wheat", "milk", "mustard"],
    additives: [],
    novaGroup: 4,
    dataConfidence: "medium",
    createdAt: now,
  },
  {
    id: "demo-yogurt",
    source: "demo",
    name: "High-Protein Greek Yogurt",
    brand: "Demo Dairy",
    servingSize: "1 pot (170g)",
    servingGrams: 170,
    nutrition: {
      calories: 130,
      protein: 17,
      carbs: 9,
      sugar: 6,
      fat: 2,
      saturatedFat: 1,
      fibre: 0,
      sodium: 60,
    },
    ingredients: "Strained milk, live cultures.",
    allergens: ["milk"],
    additives: [],
    nutriscore: "a",
    novaGroup: 2,
    dataConfidence: "high",
    createdAt: now,
  },
  {
    id: "demo-salad",
    source: "demo",
    name: "Wholegrain Chicken Salad Bowl",
    brand: "Demo Kitchen",
    servingSize: "1 bowl (380g)",
    servingGrams: 380,
    nutrition: {
      calories: 480,
      protein: 32,
      carbs: 48,
      sugar: 6,
      fat: 16,
      saturatedFat: 3,
      fibre: 9,
      sodium: 520,
    },
    ingredients:
      "Brown rice, grilled chicken, mixed greens, cherry tomatoes, cucumber, chickpeas, olive oil, lemon, herbs.",
    allergens: [],
    additives: [],
    nutriscore: "a",
    novaGroup: 1,
    dataConfidence: "high",
    createdAt: now,
  },
  {
    id: "demo-energy",
    source: "demo",
    name: "Sugar Rush Energy Drink",
    brand: "Demo Drinks",
    servingSize: "1 can (330ml)",
    nutrition: {
      calories: 160,
      protein: 0,
      carbs: 40,
      sugar: 39,
      fat: 0,
      saturatedFat: 0,
      fibre: 0,
      sodium: 220,
    },
    ingredients:
      "Carbonated water, sugar, glucose, acidifier (citric acid), taurine, caffeine, colour (E150d), flavourings.",
    allergens: [],
    additives: ["E150d", "taurine", "caffeine"],
    nutriscore: "e",
    novaGroup: 4,
    dataConfidence: "high",
    createdAt: now,
  },
  {
    id: "demo-pork",
    source: "demo",
    name: "6 Pork Sausages",
    brand: "Finnebrogue Naked",
    servingSize: "1 sausage",
    nutrition: {
      calories: 227,
      protein: 15.6,
      carbs: 0.2,
      sugar: 0.2,
      fat: 18.0,
      saturatedFat: 6.4,
      fibre: 1.5,
      sodium: 524,
    },
    ingredients:
      "Pork, Water, Sea Salt, Flavouring, Rice Flour, Chickpea Flour, Ground Spices (Coriander, White Pepper, Nutmeg), Dried Onion, Antioxidant: Ascorbic Acid; Salt, Cornflour, Dextrose. Sausages filled into natural vegetable casings.",
    allergens: [],
    additives: ["e300"],
    nutriscore: "d",
    novaGroup: 4,
    dataConfidence: "high",
    createdAt: now,
  }
];
